/**
 * i18n (Internationalization) Utility
 *
 * Simple translation helper for UI strings
 * Supports en-US and zh-CN locales
 */

export type Locale = 'en-US' | 'zh-CN';

interface Translations {
  [key: string]: {
    [locale: string]: string;
  };
}

const translations: Translations = {
  search: {
    'en-US': 'Search',
    'zh-CN': '搜索'
  },
  foundResults: {
    'en-US': 'Found {count} results',
    'zh-CN': '找到 {count} 个结果'
  },
  foundResult: {
    'en-US': 'Found {count} result',
    'zh-CN': '找到 {count} 个结果'
  },
  aiDisclaimer: {
    'en-US': 'Content generated by SNI Agent AI. Please verify important information.',
    'zh-CN': '内容由 SNI Agent AI 生成，请核查重要信息。'
  },
  pro: {
    'en-US': 'Pro',
    'zh-CN': 'Pro'
  },
  submit: {
    'en-US': 'Submit',
    'zh-CN': '提交'
  },
  processing: {
    'en-US': 'Processing',
    'zh-CN': '处理中'
  },
  enterQuery: {
    'en-US': 'Enter SNI domain (e.g., example.com)',
    'zh-CN': '输入 SNI 域名（例如：example.com）'
  },
  newLine: {
    'en-US': 'New line',
    'zh-CN': '换行'
  }
};

/**
 * Translate a key to the specified locale
 * Supports simple variable interpolation using {variable} syntax
 */
export function t(key: string, locale: Locale = 'en-US', vars?: Record<string, any>): string {
  const translation = translations[key]?.[locale] || translations[key]?.['en-US'] || key;

  if (!vars) {
    return translation;
  }

  // Replace {variable} with actual values
  return Object.keys(vars).reduce((result, varKey) => {
    return result.replace(new RegExp(`\\{${varKey}\\}`, 'g'), String(vars[varKey]));
  }, translation);
}

/**
 * Get result count text with proper pluralization
 */
export function getResultCountText(count: number, locale: Locale = 'en-US'): string {
  if (locale === 'en-US') {
    return count === 1
      ? t('foundResult', locale, { count })
      : t('foundResults', locale, { count });
  }
  // Chinese doesn't have pluralization
  return t('foundResults', locale, { count });
}
